# kafka-components/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Release.Namespace }}
data:
  server.properties: |
{{ .Files.Get .Values.kafka.server.file | indent 4 }}