# kafka-components/Chart.yaml
apiVersion: v2
name: kafka
description: A Helm chart for kafka backend
type: application
version: 0.1.0
appVersion: "1.1.0"
dependencies:
  - name: generic-kafka-backend
    version: 0.1.0
    repository: https://raw.githubusercontent.com/MiletoCarmelo/DEVOPS_HELM_generic_kafka_backend/github-pages
    alias: kafka