# kafka-components/values.dev.yaml

kafka:
  module: kafka
  environment: dev
  replicas: 1
  zookeeper:
    enabled: true
    replicaCount: 1

  # Configuration des partitions et réplicas pour le topic
  topics:
    - name: "price-data"
      partitions: 3
      replicationFactor: 1  # Assurez-vous que ce nombre est inférieur ou égal au nombre de réplicas Kafka

kafka-consumer:
  kafkaBootstrapServers: "kafka-dev-service.kafka-dev.svc.cluster.local:9092"

kafka-monitoring:
  serviceMonitor:
    enabled: true
    namespace: kafka-dev
    interval: 30s
  prometheusRules:
    enabled: true

# Configurations supplémentaires pour Zookeeper et Kafka
zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi