# kafka-components/values.dev.yaml

kafka:
  module: kafka
  environment: dev
  replicas: 1

  # Configuration des partitions et réplicas pour le topic
  # Liste des topics à créer côté Kafka backend
  topics:
    - name: "finance-price-stream"
      partitions: 3
      replicationFactor: 1  # Assurez-vous que ce nombre est inférieur ou égal au nombre de réplicas Kafka
    - name: "order-data"
      partitions: 2
      replicationFactor: 1

kafka-consumer:
  kafkaBootstrapServers: "kafka-dev-service.kafka-dev.svc.cluster.local:9092"

kafka-monitoring:
  serviceMonitor:
    enabled: true
    namespace: kafka-dev
    interval: 30s
  prometheusRules:
    enabled: true