# kafka-components/values.dev.yaml
kafka:
  module: kafka
  environment: dev
  replicas: 3
  zookeeper:
    enabled: true
    replicaCount: 3

kafka-consumer:
  kafkaBootstrapServers: "kafka-dev-service.kafka-dev.svc.cluster.local:9092"

kafka-monitoring:
  serviceMonitor:
    enabled: true
    namespace: kafka-dev
    interval: 30s
  prometheusRules:
    enabled: true

prometheus:
  enabled: true
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
  alertmanager:
    enabled: true
  grafana:
    enabled: true