# kafka-components/values.dev.yaml
kafka:
  module: kafka
  environment: dev
  replicas: 2
  zookeeper:
    enabled: true
    replicaCount: 2

kafka-consumer:
  kafkaBootstrapServers: "kafka-dev-service.kafka-dev.svc.cluster.local:9092"

kafka-monitoring:
  serviceMonitor:
    enabled: true
    namespace: kafka-dev
    interval: 30s
  prometheusRules:
    enabled: true